GET http://localhost:3001/info
Accept: application/json

###
GET http://localhost:3001/api/persons
Accept: application/json

###

DELETE http://localhost:3001/api/persons/:id

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Alice Kippok",
  "number": "182-333-9973"
}


